CREATE TABLE cars (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    brand VARCHAR(255) NOT NULL,
    model_name VARCHAR(255) NOT NULL,
    registration_number VARCHAR(255) NOT NULL,
    year_of_production INT NOT NULL,
    colour VARCHAR(20) NOT NULL,
    car_status VARCHAR(20) NOT NULL,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);